-- Create contacts table for MarketFlow CRM
CREATE TABLE IF NOT EXISTS contacts (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL DEFAULT '',
  website TEXT DEFAULT '',
  platform TEXT DEFAULT '',
  budget NUMERIC DEFAULT 0,
  rating INTEGER DEFAULT 1,
  contact_person TEXT DEFAULT '',
  seller TEXT DEFAULT '',
  service TEXT DEFAULT '',
  status TEXT DEFAULT 'pending',
  start_date TEXT DEFAULT '',
  end_date TEXT DEFAULT '',
  comment TEXT DEFAULT '',
  has_report BOOLEAN DEFAULT false,
  phone TEXT DEFAULT '',
  emails TEXT DEFAULT '',
  google_ads_customer_id TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;

-- Allow public access (anon key) for now
CREATE POLICY "Allow all access" ON contacts FOR ALL USING (true) WITH CHECK (true);

-- Insert all contacts
INSERT INTO contacts (name, website, platform, budget, rating, contact_person, seller, service, status, start_date, end_date, comment, has_report) VALUES
('AC-Verkstan', 'https://acverkstan.se/', 'Wordpress', 8, 1, '', '', 'SEO', 'active', '2026-01-15', '', '', false),
('Samuelssons Tak', 'https://samuelssonstak.se/', 'Wordpress', 30, 1, '', '', 'SEO', 'active', '2026-01-20', '', '', false),
('Maskinaffären', 'https://www.maskinaffaren.se/', 'Wordpress', 30, 1, '', 'Jonas', 'SEO', 'active', '2026-02-01', '', '', false),
('Mavi Bygg', 'https://www.mavi-bygg.se/', 'Wordpress', 30, 1, '', 'Alban Krasnici', 'SEO', 'active', '2026-02-01', '', '', false),
('My Camping', 'https://mycamping.se/', 'Control Tower', 40, 3, '', 'Ulf Eriksson', 'SEO + ADS', 'active', '2026-01-10', '', 'ADS sesongbaserad - campingar i blekinge, sölvesborg, karlshamn.', true),
('Nilekedjan Kalmar', 'https://nilekedjan.se/', 'Wordpress', 20, 1, '', '', 'SEO', 'active', '2026-02-15', '', '', false),
('Novum Rentals', 'https://novumrentals.com/', 'PHP', 120, 2, '', '', 'SEO', 'active', '2026-01-05', '', '', true),
('Nya Golvbolaget', 'https://www.nyagolvbolaget.se/', 'Wordpress', 20, 1, '', 'Ulf Eriksson', 'SEO', 'active', '2026-02-01', '', 'Främst golvslipning lokalt', false),
('Östgöta Lackering', 'https://ostgotalackering.se/', 'Wordpress', 0, 1, '', '', 'SEO', 'pending', '', '', '', false),
('Ostkustens Glas & Montage', 'https://www.ogmab.se/', 'Wordpress', 60, 1, '', 'Ulf Eriksson', 'SEO', 'active', '2026-01-15', '', 'Kund svarar ej enligt Ulf, vill synas västervik-karlskrona, kalmar lokalt.', false),
('Putsman', 'https://putsman.se/', 'Wordpress', 25, 1, '', '', 'SEO', 'active', '2026-02-10', '', '', false),
('Rostskyddsmetoder', 'https://rostskyddsmetoder.se/', 'Wordpress', 20, 1, '', '', 'SEO', 'active', '2026-02-20', '', '', false),
('S Karlssons', 'https://www.skarlssons.se/', 'Wordpress', 20, 1, '', '', 'SEO', 'active', '2026-03-01', '', '', false),
('Samstäd & Flytt', 'https://samstad.se/', 'Wordpress', 20, 1, '', '', 'SEO', 'active', '2026-02-15', '', '', false),
('Saxnäs Golf', 'https://saxnasgolf.se/', 'Wordpress', 30, 1, '', '', 'SEO', 'active', '2026-01-20', '', '', false),
('Lundhs Hund', 'https://www.lundhs-hund.se/', 'Wordpress', 108, 3, '', '', 'SEO', 'active', '2026-01-01', '', '', true),
('Småland Sportfiske', 'https://www.smaland-sportfiske.com/sv/', 'Wordpress', 0, 1, '', '', 'SEO', 'pending', '', '', '', false),
('Smålandstak', 'https://smalandstak.se/', 'Wordpress', 5, 1, '', '', 'SEO', 'active', '2026-03-01', '', '', false),
('Specialsnickeriet', 'https://specialsnickeriet.se/', 'Wordpress', 36, 1, '', '', 'SEO', 'active', '2026-02-01', '', '', false),
('Stekhuset Kalmar', 'https://stekhusetikalmar.se/', 'Wordpress', 12, 1, '', '', 'SEO', 'active', '2026-02-15', '', '', false),
('Taxi Nora', 'https://taxinora.se/', 'HTML', 12, 1, '', '', 'SEO', 'active', '2026-02-20', '', '', false),
('Teknicare', 'https://teknicare.se/', 'Wordpress', 0, 1, '', '', 'SEO', 'pending', '', '', '', false),
('TokigeTure', 'https://www.tokigeture.se/', 'Wordpress', 50, 2, '', '', 'SEO', 'active', '2026-01-10', '', '', false),
('Ventim', 'https://ventim.se/', 'Lithium', 120, 3, '', 'Ulf Eriksson', 'SEO', 'paused', '2026-01-05', '', '"Väntande" kund vet inte vad de vill', true),
('WB Säkerhet', 'https://wblas.se', 'Wordpress', 30, 1, '', '', 'SEO', 'active', '2026-02-01', '', '', false),
('WTak', 'https://wtak.se/', 'Wordpress', 36, 1, '', 'Ulf Eriksson', 'SEO', 'active', '2026-02-15', '', 'Papptak, listtäckning', false),
('Sthlms Vedlager & Slipptippen', 'https://www.stockholmsvedlager.se/', 'Wordpress', 120, 3, '', '', 'SEO', 'active', '2026-01-01', '', '', true),
('Etec', 'https://etecteknikutbildning.se/', 'Wordpress', 50, 2, '', '', 'SEO', 'active', '2026-01-15', '', '', true),
('Ryssby', 'https://ryssbygymnasiet.se/', 'Wordpress', 60, 2, '', '', 'SEO', 'active', '2026-01-10', '', '', true),
('Magasin Severin', 'https://magasinseverin.se/', 'GoBrave', 50, 2, '', '', 'SEO', 'active', '2026-02-01', '', '', false),
('LS Solfilm', 'https://js-solfilm.se/', 'Wordpress', 12, 1, '', '', 'SEO', 'active', '2026-03-01', '', '', false),
('Advanced Vacuum', 'http://advancedvacuum.se/', 'Wordpress', 30, 1, '', '', 'SEO', 'active', '2026-02-10', '', '', false),
('Glasnet', 'https://www.glasnet.nu/', 'Wordpress', 60, 2, '', '', 'SEO', 'active', '2026-01-20', '', '', true),
('Åkerbo El', 'https://akerboel.se/', 'Wordpress', 20, 1, '', '', 'SEO', 'active', '2026-02-15', '', '', false),
('Autobody Stockholm', 'https://autobody.se', 'One Page Builder', 48, 1, '', '', 'SEO', 'active', '2026-01-15', '', '', false),
('Benavides Golvservice', 'https://benavidesgolvservice.se/', 'Wordpress', 24, 1, '', '', 'SEO', 'active', '2026-02-01', '', '', false),
('Björklunds Fasad & Måleri', 'https://bjorklundsmaleri.se/', 'Wordpress', 0, 1, '', '', 'SEO', 'pending', '', '', '', false),
('Björnssons Bygg', 'https://bjornssonsbygg.se/', 'Wordpress', 0, 1, '', '', 'SEO', 'pending', '', '', '', false),
('Bryggan Kalmar', 'https://www.bryggankalmar.se/', 'Wordpress', 30, 1, '', '', 'SEO', 'active', '2026-02-10', '', '', false),
('Byggfirma Mats Stålgren', 'https://bfms.se/', 'Wordpress', 18, 1, '', '', 'SEO', 'active', '2026-03-01', '', '', false),
('Calmarsunds Mur och Fasad', 'https://calmarsund.se/', 'Wordpress', 30, 1, '', '', 'SEO', 'active', '2026-02-20', '', '', false),
('Ekstrands Jord och Grus', 'https://ekstrandsjordogrus.se/', 'Wordpress', 18, 1, '', '', 'SEO', 'active', '2026-02-15', '', '', false),
('En Trappa Upp', 'https://entrappaupp.eu/', 'Pagecloud', 30, 1, '', '', 'SEO', 'active', '2026-02-01', '', '', false),
('Eriksson Marine Scandinavia', 'https://www.emarin.se/', 'Wordpress', 50, 2, '', '', 'SEO', 'active', '2026-01-10', '', '', true),
('Foten', 'https://foten.se/', 'Shopify', 24, 1, '', '', 'SEO', 'active', '2026-02-20', '', '', false),
('Gamla Televerket', 'https://gamlateleverket.se/', 'Wordpress', 20, 1, '', '', 'SEO', 'active', '2026-03-01', '', '', false),
('Global Batterier', 'https://global.se/', 'Centro', 120, 3, '', '', 'SEO', 'active', '2026-01-05', '', '', true),
('LB Städ', 'https://lbstad.se/', 'Wordpress', 30, 1, '', '', 'SEO', 'active', '2026-02-01', '', '', false),
('Gottfridssons Flytt & Städ', 'https://www.gottfridssonsflytt.se/', 'Wordpress', 0, 1, '', '', 'SEO', 'pending', '', '', '', false),
('Gustafssons Glasmästeri', 'https://gustafssonsglas.se/', 'Wordpress', 20, 1, '', '', 'SEO', 'active', '2026-02-15', '', '', false),
('Gylles & Tillbors Catering', 'https://gylles.se', 'Wordpress', 20, 1, '', '', 'SEO', 'active', '2026-03-01', '', '', false),
('Hansabygg', 'https://hansabygg.se/', 'Wordpress', 50, 1, '', '', 'SEO', 'active', '2026-01-15', '', '', false),
('HJ Fritid', 'https://www.hjfritid.se/', 'Wordpress', 24, 1, '', '', 'SEO', 'active', '2026-02-10', '', '', false),
('Inrednings-shopen', 'https://inrednings-shopen.se/', 'Wordpress', 30, 1, '', '', 'SEO', 'active', '2026-02-20', '', '', false),
('Italiana Bar & Restaurang', 'https://www.italianarestaurang.se/', 'Wordpress', 24, 1, '', '', 'SEO', 'active', '2026-03-01', '', '', false),
('Kalmarsunds Plåt', 'https://www.kalmarsundsplat.se/', 'Wordpress', 30, 1, '', '', 'SEO', 'active', '2026-02-01', '', '', false),
('Kama Entreprenad', 'https://kamaentreprenad.se/', 'Wordpress', 30, 1, '', 'Ulf Eriksson', 'SEO', 'active', '2026-01-15', '', 'Löpande avtal, 5k/mån', false),
('Kim Färm', 'https://www.kimfarm.se/', 'Wordpress', 30, 1, '', '', 'SEO', 'active', '2026-02-10', '', 'Jonas kund', false),
('Klämma Plåtslageri', 'https://klämnaplätslageri.se/', 'Wordpress', 24, 1, '', '', 'SEO', 'active', '2026-02-20', '', '', false),
('Kristianopel Gästgifveri', 'https://kristianopelgastgifveri.se/', 'Wordpress', 24, 1, '', '', 'SEO', 'active', '2026-03-01', '', 'Jonas kund', false),
('KV-Bygg', 'https://k-vbygg.se/', 'Wordpress', 0, 1, '', '', 'SEO', 'pending', '', '', '', false);
